jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "This job can overlap"
  deploy:
    docker:
      - image: 'circleci/node:10'
    steps:
      - queue/until_front_of_line:
          only-on-branch: main
          time: '60'
      - run: echo "This job will not overlap"
orbs:
  queue: eddiewebb/queue@volatile
version: 2.1
workflows:
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
