orbs:
  queue: eddiewebb/queue@volatile
version: 2.1
workflows:
  build_deploy:
    jobs:
      - queue/block_workflow:
          time: '60'
      - some_other_job:
          requires:
            - queue/block_workflow
