jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo "Build started"
      - run: sleep 10
      - run: echo "Build finished"
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - queue/until_front_of_line:
          only-on-branch: main
          time: '300'
      - run: echo "Deploy started"
      - run: sleep 60
      - run: echo "Deploy completed"
orbs:
  queue: eddiewebb/queue@volatile
version: 2.1
workflows:
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
